Updated to solve issue
AttributeError : module 'tensorflow' has no attribute 'placeholder'
https://stackoverflow.com/questions/56226284/why-do-i-get-attributeerror-module-tensorflow-has-no-attribute-placeholder